#+TITLE: Tron usage
#+PROPERTY: header-args :session *shell tron curl* :results silent raw

** Contents                                                           :TOC_3:
  - [[#environment-description][Environment description]]
  - [[#requirements][Requirements]]
  - [[#credentials][Credentials]]
  - [[#address-utilities][Address Utilities]]
    - [[#generate-address][Generate address]]
    - [[#create-address][Create address]]
    - [[#validate-address][Validate address]]
  - [[#query-the-network][Query the network]]
    - [[#list-nodes][List nodes]]
    - [[#get-node-info][Get node info]]
    - [[#get-chain-parameters][Get chain parameters]]
  - [[#smart-contracts][Smart Contracts]]
    - [[#get-contract][Get contract]]
  - [[#references][References]]

** Environment description

- Deployed java-tron v4.0.1

** Requirements

- curl 7.61.1

** Credentials

Full node URL.

#+BEGIN_SRC sh
URL="http://127.0.0.1:8090"
#+END_SRC

** Address Utilities
*** Generate address

#+BEGIN_SRC sh
curl $URL/wallet/generateaddress | python -m json.tool
#+END_SRC

*** Create address

Prepare a password.

#+BEGIN_SRC sh
PASSWORD="testpassword123"
#+END_SRC

#+BEGIN_SRC sh
HEX_PASSWORD=`python -c "print('$PASSWORD'.encode('utf-8').hex())"`
#+END_SRC

Call an API method.

#+BEGIN_SRC sh
curl --request POST \
  --url $URL/wallet/createaddress \
  --header 'Content-Type: application/json' \
  --data "{\"value\":\"$HEX_PASSWORD\"}" | python -m json.tool
#+END_SRC

Use the base58checkAddress field as ADDRESS_B58 and value as ADDRESS_HEX.

#+BEGIN_SRC sh
ADDRESS_B58="..."
ADDRESS_HEX="..."
#+END_SRC

*** Validate address

#+BEGIN_SRC sh
ADDRESS=""
#+END_SRC

#+BEGIN_SRC sh
curl --request POST \
  --url $URL/wallet/validateaddress \
  --header 'Content-Type: application/json' \
  --data "{\"address\":\"$ADDRESS\"}" | python -m json.tool
#+END_SRC

** Query the network
*** List nodes

#+BEGIN_SRC sh
curl $URL/wallet/listnodes | python -m json.tool
#+END_SRC

*** Get node info

#+BEGIN_SRC sh
curl $URL/wallet/getnetworkinfo | python -m json.tool
#+END_SRC

*** Get chain parameters

#+BEGIN_SRC sh
curl $URL/wallet/getchainparameters | python -m json.tool
#+END_SRC

** Smart Contracts
*** Get contract

#+BEGIN_SRC sh
CONTRACT_ADDRESS=""
#+END_SRC

#+BEGIN_SRC sh
VISIBLE="true"
#+END_SRC

#+BEGIN_SRC sh
curl --request POST \
  --url $URL/wallet/getcontract \
  --header 'Content-Type: application/json' \
  --data "{\"value\":\"$CONTRACT_ADDRESS\",\"visible\":$VISIBLE}"
#+END_SRC

** References

1. https://developers.tron.network/reference
